services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: modernizer
      POSTGRES_PASSWORD: modernizer
      POSTGRES_DB: modernizer
    ports:
        - "5433:5432"
    volumes:
        - ./migrations:/docker-entrypoint-initdb.d:ro
        - pgdata:/var/lib/postgresql/data
        - ./samples:/samples:ro
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U modernizer -d modernizer"]
        interval: 5s
        timeout: 3s
        retries: 10
volumes:
  pgdata: