[project]
name = "modernizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "IsacAlves", email = "isac.carmo@singletech.com.br" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "fastapi>=0.142.2",
    "google-genai>=2.26.0",
    "langgraph>=1.2.12",
    "langgraph-cli[inmem]>=0.4.32",
    "pglast>=8.4",
    "psycopg[binary]>=3.3.6",
    "ruff>=0.16.9",
    "sqlglot>=30.21.0",
]

[project.scripts]
modernizer = "modernizer:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
